import { C1PagePresence } from "./c1-page-presence";
import { C3PageWatch } from "./c3-page-watch";
import { X1PageExport } from "./x1-page-export";
import type { PageHeaderUnitProps } from "./types";

/** Wave 2 units' page-header slots, in a fixed order. Units do not edit this file. */
export function PageHeaderUnits(props: PageHeaderUnitProps) {
  return (
    <>
      <C1PagePresence {...props} />
      <C3PageWatch {...props} />
      <X1PageExport {...props} />
    </>
  );
}

export type { PageHeaderUnitProps } from "./types";
