-- Workspace OS S6 Flow, M14a/b: workflows as a step graph (epic #199).
--
-- Extends the existing automation tables instead of replacing them, so every
-- rule written before this keeps running exactly as it did:
--
--   workflow_rule       gains `engine`. Existing rows are `rules_v1` and are
--                       still matched by fireWorkflows(); a `graph_v2` row
--                       carries a step graph and is run by the workflow
--                       runner job. Its trigger_event is `object_event`, which
--                       no legacy event type equals, so the old matcher never
--                       picks it up.
--   workflow_execution  gains the run columns a graph run needs. A legacy row
--                       keeps its three outcomes; a graph run adds `running`,
--                       `waiting`, `succeeded` and `stopped`. A graph run never
--                       has a notification payload, so the legacy retry job
--                       (outcome failed and payload not null) never sees one.
--   workflow_execution_step  new: one row per step a run took, with its input,
--                       output, timing and error. Admin read, like runs.
--   workflow_event_cursor    new: where the runner has read the event stream
--                       up to. Service role only.
--
-- app.can_as answers the one access question for a named person, so a run can
-- act with its owner's permissions (never more) while being labelled as an
-- automation. It is callable by the service role only.

-- ---------------------------------------------------------------------------
-- workflow_rule
-- ---------------------------------------------------------------------------

alter table public.workflow_rule
  add column if not exists engine text not null default 'rules_v1',
  add column if not exists graph jsonb,
  add column if not exists description text,
  add column if not exists run_as_user_id uuid references public.user_profile (id) on delete set null,
  add column if not exists updated_by uuid references public.user_profile (id) on delete set null,
  add column if not exists definition_version int not null default 1;

alter table public.workflow_rule
  add constraint workflow_rule_engine_check check (engine in ('rules_v1', 'graph_v2')),
  add constraint workflow_rule_graph_required check (engine <> 'graph_v2' or graph is not null),
  add constraint workflow_rule_description_length check (description is null or char_length(description) <= 1000),
  add constraint workflow_rule_definition_version_positive check (definition_version >= 1);

comment on column public.workflow_rule.engine is
  'rules_v1 = the original trigger/condition/notify rule; graph_v2 = a step graph run by the workflow-events job.';
comment on column public.workflow_rule.graph is
  'The step graph (src/features/workflows/graph.ts). Required when engine is graph_v2.';
comment on column public.workflow_rule.run_as_user_id is
  'Whose permissions a graph run acts with. Its changes are labelled as the automation, not this person.';

create index if not exists idx_workflow_rule_engine
  on public.workflow_rule (organization_id, engine) where enabled;

-- ---------------------------------------------------------------------------
-- workflow_execution
-- ---------------------------------------------------------------------------

alter table public.workflow_execution
  add column if not exists engine text not null default 'rules_v1',
  add column if not exists run_number bigint generated by default as identity,
  add column if not exists trigger_event_id uuid,
  add column if not exists trigger_payload jsonb,
  add column if not exists is_test boolean not null default false,
  add column if not exists started_at timestamptz,
  add column if not exists finished_at timestamptz,
  add column if not exists actor_kind text,
  add column if not exists actor_id text;

alter table public.workflow_execution
  drop constraint if exists workflow_execution_outcome_check;
alter table public.workflow_execution
  add constraint workflow_execution_outcome_check check (
    outcome in ('notified', 'skipped', 'failed', 'running', 'waiting', 'succeeded', 'stopped')
  ),
  add constraint workflow_execution_engine_check check (engine in ('rules_v1', 'graph_v2')),
  add constraint workflow_execution_actor_kind_check check (
    actor_kind is null or actor_kind in ('person', 'team', 'automation', 'integration', 'system')
  );

comment on column public.workflow_execution.run_number is
  'The number people use for a run ("Run #1642").';
comment on column public.workflow_execution.trigger_event_id is
  'The event that started the run. With rule_id it is unique, so re-reading the stream never runs a rule twice.';

-- At-least-once reading of the event stream becomes exactly-once running.
create unique index if not exists workflow_execution_rule_event_once
  on public.workflow_execution (rule_id, trigger_event_id)
  where trigger_event_id is not null and not is_test;
create unique index if not exists workflow_execution_run_number
  on public.workflow_execution (run_number);

-- ---------------------------------------------------------------------------
-- workflow_execution_step
-- ---------------------------------------------------------------------------

create table public.workflow_execution_step (
  id uuid primary key default gen_random_uuid(),
  execution_id uuid not null references public.workflow_execution (id) on delete cascade,
  organization_id uuid not null references public.organization (id) on delete cascade,
  position int not null check (position >= 0),
  step_id text not null check (char_length(step_id) between 1 and 64),
  step_kind text not null check (char_length(step_kind) between 1 and 32),
  status text not null check (status in ('running', 'succeeded', 'failed', 'skipped', 'waiting')),
  input jsonb,
  output jsonb,
  error text check (error is null or char_length(error) <= 2000),
  attempt int not null default 1 check (attempt >= 1),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  unique (execution_id, position)
);

comment on table public.workflow_execution_step is
  'One row per step a graph run took: what went in, what came out, how long it took and why it failed.';

create index idx_workflow_execution_step_org
  on public.workflow_execution_step (organization_id, started_at desc);

alter table public.workflow_execution_step enable row level security;

-- The same audience as the run it belongs to (workflow_execution_admin_read).
create policy workflow_execution_step_admin_read on public.workflow_execution_step
  for select to authenticated
  using (app.is_org_admin(organization_id));
-- No insert, update or delete policy: written by the workflow runner through
-- the service role only.

-- ---------------------------------------------------------------------------
-- workflow_event_cursor
-- ---------------------------------------------------------------------------

create table public.workflow_event_cursor (
  consumer text primary key check (char_length(consumer) between 1 and 64),
  last_created_at timestamptz,
  last_id uuid,
  updated_at timestamptz not null default now()
);

comment on table public.workflow_event_cursor is
  'How far the workflow runner has read the event stream. Replaced by object_event_cursor when object_event lands (M9a).';

alter table public.workflow_event_cursor enable row level security;
-- No policies: nobody reads or writes it through the API.

-- ---------------------------------------------------------------------------
-- app.can_as: the access check, answered for a named person
-- ---------------------------------------------------------------------------

-- p_assurance is the sign-in level to ask at. Owners and admins need the
-- two-step level (aal2) for anything but reading. aal2 is only used when the
-- person has a live verified second factor (as app.is_org_admin requires);
-- otherwise the question is asked at aal1. So it never lends someone a level
-- they could not reach themselves.
-- Workflows ask at aal2: only an admin in a two-step session can save one.
create or replace function app.can_as(
  p_user uuid,
  p_object uuid,
  p_capability text,
  p_assurance text default 'aal1'
)
returns boolean
language plpgsql volatile security definer
set search_path = ''
as $$
declare
  v_claims text := current_setting('request.jwt.claims', true);
  v_sub text := current_setting('request.jwt.claim.sub', true);
  v_role text := current_setting('request.jwt.claim.role', true);
  v_result boolean := false;
  v_assurance text := p_assurance;
begin
  if p_user is null or p_object is null or p_assurance is null
     or p_assurance not in ('aal1', 'aal2') then
    return false;
  end if;
  if v_assurance = 'aal2' and not exists (
    select 1 from auth.mfa_factors f
    where f.user_id = p_user and f.factor_type = 'totp' and f.status = 'verified'
  ) then
    v_assurance := 'aal1';
  end if;

  perform set_config('request.jwt.claims',
    json_build_object('sub', p_user::text, 'role', 'authenticated', 'aal', v_assurance)::text, true);
  perform set_config('request.jwt.claim.sub', p_user::text, true);
  perform set_config('request.jwt.claim.role', 'authenticated', true);
  begin
    v_result := coalesce(app.can(p_object, p_capability), false);
  exception when others then
    v_result := false;
  end;
  perform set_config('request.jwt.claims', coalesce(v_claims, ''), true);
  perform set_config('request.jwt.claim.sub', coalesce(v_sub, ''), true);
  perform set_config('request.jwt.claim.role', coalesce(v_role, ''), true);
  return v_result;
end;
$$;

create or replace function public.can_as(
  p_user uuid,
  p_object uuid,
  p_capability text,
  p_assurance text default 'aal1'
)
returns boolean
language sql volatile security definer
set search_path = ''
as $$
  select app.can_as(p_user, p_object, p_capability, p_assurance);
$$;

revoke all on function app.can_as(uuid, uuid, text, text) from public, anon, authenticated;
revoke all on function public.can_as(uuid, uuid, text, text) from public, anon, authenticated;
grant execute on function app.can_as(uuid, uuid, text, text) to service_role;
grant execute on function public.can_as(uuid, uuid, text, text) to service_role;

comment on function app.can_as(uuid, uuid, text, text) is
  'app.can for a named person at a given sign-in level, for the workflow runner and API tokens. Service role only.';

-- ---------------------------------------------------------------------------
-- The runner job: reads new events and runs matching graph workflows.
-- ---------------------------------------------------------------------------

insert into public.job_definition (name, description, schedule, queue, enabled, batch_size, max_attempts)
values
  ('workflow-events',
   'Runs step-graph workflows for new events. Does nothing while wos_workflows_v2 is off.',
   '* * * * *', null, true, 100, 3)
on conflict (name) do update
  set description = excluded.description,
      schedule = excluded.schedule;

do $$
declare
  j record;
begin
  for j in select name, schedule from public.job_definition where name = 'workflow-events'
  loop
    perform cron.unschedule(j.name)
      where exists (select 1 from cron.job c where c.jobname = j.name);
    perform cron.schedule(j.name, j.schedule,
      format('select app.dispatch_job(%L)', j.name));
  end loop;
end;
$$;
