"use client";

import * as React from "react";
import type { LensT } from "@/features/lenses/i18n";
import type { ViewLayout } from "@/features/lenses/view-block/schema";
import { D3LayoutSettings, d3LayoutLabel, renderD3Layout } from "./d3-layouts";
import { D4LayoutSettings, d4LayoutLabel, renderD4Layout } from "./d4-layouts";
import { d3PropsShape } from "./d3.ids";
import { d4PropsShape } from "./d4.ids";
import type { LayoutRenderContext, LayoutSettingsProps } from "./types";

/**
 * The view block's wave 2 layout slots (D3, D4). Units do not edit this file.
 */

export type { LayoutRenderContext, LayoutSettingsProps } from "./types";

/** A unit layout's body, or undefined for the block's own layouts. */
export function renderUnitLayout(ctx: LayoutRenderContext): React.ReactNode | undefined {
  const d3 = renderD3Layout(ctx);
  if (d3 !== undefined) return d3;
  return renderD4Layout(ctx);
}

export function UnitLayoutSettings(props: LayoutSettingsProps) {
  return (
    <>
      <D3LayoutSettings {...props} />
      <D4LayoutSettings {...props} />
    </>
  );
}

/** A unit layout's name, or null for the block's own layouts. */
export function unitLayoutLabel(layout: ViewLayout, t: LensT): string | null {
  return d3LayoutLabel(layout, t) ?? d4LayoutLabel(layout, t);
}

/** The keys of the props the units own. */
export const UNIT_PROP_KEYS: readonly string[] = [...Object.keys(d3PropsShape), ...Object.keys(d4PropsShape)];

/** The unit-owned props in a parsed block, for the settings draft. */
export function pickUnitProps(value: object | null): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  if (!value) return out;
  for (const key of UNIT_PROP_KEYS) {
    const v = (value as Record<string, unknown>)[key];
    if (v !== undefined) out[key] = v;
  }
  return out;
}
